version: '3.8'

services:
  cms:
    build: .
    container_name: heaven-dolls-cms
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=heaven_dolls_cms
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi_password
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - heaven-dolls

  postgres:
    image: postgres:15-alpine
    container_name: heaven-dolls-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=heaven_dolls_cms
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - heaven-dolls

  redis:
    image: redis:7-alpine
    container_name: heaven-dolls-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - heaven-dolls

  nginx:
    image: nginx:alpine
    container_name: heaven-dolls-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - cms
    networks:
      - heaven-dolls

volumes:
  postgres_data:
  redis_data:

networks:
  heaven-dolls:
    driver: bridge